###############
## 
####

GPU: [2,3]

VERBOSE: True

MODEL:
  MODE: 'Denoising'
  SESSION: 'MPRNet-wNLE'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 36
  NUM_EPOCHS: 200
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-5 #2e-4
  LR_MIN: 1e-6 #1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 32
  VAL_PS: None
  TRAIN_DIR: '/home/local/PARTNERS/yl715/data/garyli/p32x32x32_patches_1_8_1_4_full_ct_SUV_CountsConcentrationinMask' # path to training data
  VAL_DIR: '/home/local/PARTNERS/yl715/data/garyli/p32x32x32_patches_1_8_1_4_full_ct_test_SUV_CountsConcentrationinMask'     # path to validation data
  SAVE_DIR: '/home/local/PARTNERS/yl715/prelim_HO_data/3DORSOnly_MSEEDGEModulatedbypcInfo_PS32_nfeat96_1_8_to_Full_wpcInfo_ModEncDecORS_PET_OneMLP_FullDS_l1_SUV_v3'          # path to save models and images
  # SAVE_IMAGES: False
